services:
  ResourceExecution.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      # Connection Strings & RabbitMQ
      - ConnectionStrings__Database=Server=sqlserver;Database=ResourceExecutionDB;User Id=sa;Password=Your_Password123!;TrustServerCertificate=True
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - RabbitMq__ExchangeName=clean_architecture_integration_exchange
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    environment:
      - MSSQL_SA_PASSWORD=Your_Password123!
    ports:
      - "1433:1433"

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"